/*
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_ticketing_client

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
	"time"
)

// Linger please
var (
	_ _context.Context
)

// CollectionsApiService CollectionsApi service
type CollectionsApiService service

type ApiCollectionsListRequest struct {
	ctx _context.Context
	ApiService *CollectionsApiService
	xAccountToken *string
	collectionType *string
	createdAfter *time.Time
	createdBefore *time.Time
	cursor *string
	includeDeletedData *bool
	includeRemoteData *bool
	modifiedAfter *time.Time
	modifiedBefore *time.Time
	pageSize *int32
	parentCollectionId *string
	remoteFields *string
	remoteId *string
	showEnumOrigins *string
}

func (r ApiCollectionsListRequest) XAccountToken(xAccountToken string) ApiCollectionsListRequest {
	r.xAccountToken = &xAccountToken
	return r
}
func (r ApiCollectionsListRequest) CollectionType(collectionType string) ApiCollectionsListRequest {
	r.collectionType = &collectionType
	return r
}
func (r ApiCollectionsListRequest) CreatedAfter(createdAfter time.Time) ApiCollectionsListRequest {
	r.createdAfter = &createdAfter
	return r
}
func (r ApiCollectionsListRequest) CreatedBefore(createdBefore time.Time) ApiCollectionsListRequest {
	r.createdBefore = &createdBefore
	return r
}
func (r ApiCollectionsListRequest) Cursor(cursor string) ApiCollectionsListRequest {
	r.cursor = &cursor
	return r
}
func (r ApiCollectionsListRequest) IncludeDeletedData(includeDeletedData bool) ApiCollectionsListRequest {
	r.includeDeletedData = &includeDeletedData
	return r
}
func (r ApiCollectionsListRequest) IncludeRemoteData(includeRemoteData bool) ApiCollectionsListRequest {
	r.includeRemoteData = &includeRemoteData
	return r
}
func (r ApiCollectionsListRequest) ModifiedAfter(modifiedAfter time.Time) ApiCollectionsListRequest {
	r.modifiedAfter = &modifiedAfter
	return r
}
func (r ApiCollectionsListRequest) ModifiedBefore(modifiedBefore time.Time) ApiCollectionsListRequest {
	r.modifiedBefore = &modifiedBefore
	return r
}
func (r ApiCollectionsListRequest) PageSize(pageSize int32) ApiCollectionsListRequest {
	r.pageSize = &pageSize
	return r
}
func (r ApiCollectionsListRequest) ParentCollectionId(parentCollectionId string) ApiCollectionsListRequest {
	r.parentCollectionId = &parentCollectionId
	return r
}
func (r ApiCollectionsListRequest) RemoteFields(remoteFields string) ApiCollectionsListRequest {
	r.remoteFields = &remoteFields
	return r
}
func (r ApiCollectionsListRequest) RemoteId(remoteId string) ApiCollectionsListRequest {
	r.remoteId = &remoteId
	return r
}
func (r ApiCollectionsListRequest) ShowEnumOrigins(showEnumOrigins string) ApiCollectionsListRequest {
	r.showEnumOrigins = &showEnumOrigins
	return r
}

func (r ApiCollectionsListRequest) Execute() (PaginatedCollectionList, *_nethttp.Response, error) {
	return r.ApiService.CollectionsListExecute(r)
}

/*
 * CollectionsList Method for CollectionsList
 * Returns a list of `Collection` objects.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiCollectionsListRequest
 */
func (a *CollectionsApiService) CollectionsList(ctx _context.Context) ApiCollectionsListRequest {
	return ApiCollectionsListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

/*
 * Execute executes the request
 * @return PaginatedCollectionList
 */
func (a *CollectionsApiService) CollectionsListExecute(r ApiCollectionsListRequest) (PaginatedCollectionList, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  PaginatedCollectionList
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CollectionsApiService.CollectionsList")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/collections"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xAccountToken == nil {
		return localVarReturnValue, nil, reportError("xAccountToken is required and must be specified")
	}

	if r.collectionType != nil {
		localVarQueryParams.Add("collection_type", parameterToString(*r.collectionType, ""))
	}
	if r.createdAfter != nil {
		localVarQueryParams.Add("created_after", parameterToString(*r.createdAfter, ""))
	}
	if r.createdBefore != nil {
		localVarQueryParams.Add("created_before", parameterToString(*r.createdBefore, ""))
	}
	if r.cursor != nil {
		localVarQueryParams.Add("cursor", parameterToString(*r.cursor, ""))
	}
	if r.includeDeletedData != nil {
		localVarQueryParams.Add("include_deleted_data", parameterToString(*r.includeDeletedData, ""))
	}
	if r.includeRemoteData != nil {
		localVarQueryParams.Add("include_remote_data", parameterToString(*r.includeRemoteData, ""))
	}
	if r.modifiedAfter != nil {
		localVarQueryParams.Add("modified_after", parameterToString(*r.modifiedAfter, ""))
	}
	if r.modifiedBefore != nil {
		localVarQueryParams.Add("modified_before", parameterToString(*r.modifiedBefore, ""))
	}
	if r.pageSize != nil {
		localVarQueryParams.Add("page_size", parameterToString(*r.pageSize, ""))
	}
	if r.parentCollectionId != nil {
		localVarQueryParams.Add("parent_collection_id", parameterToString(*r.parentCollectionId, ""))
	}
	if r.remoteFields != nil {
		localVarQueryParams.Add("remote_fields", parameterToString(*r.remoteFields, ""))
	}
	if r.remoteId != nil {
		localVarQueryParams.Add("remote_id", parameterToString(*r.remoteId, ""))
	}
	if r.showEnumOrigins != nil {
		localVarQueryParams.Add("show_enum_origins", parameterToString(*r.showEnumOrigins, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-Account-Token"] = parameterToString(*r.xAccountToken, "")
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["tokenAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCollectionsRetrieveRequest struct {
	ctx _context.Context
	ApiService *CollectionsApiService
	xAccountToken *string
	id string
	includeRemoteData *bool
	remoteFields *string
	showEnumOrigins *string
}

func (r ApiCollectionsRetrieveRequest) XAccountToken(xAccountToken string) ApiCollectionsRetrieveRequest {
	r.xAccountToken = &xAccountToken
	return r
}
func (r ApiCollectionsRetrieveRequest) IncludeRemoteData(includeRemoteData bool) ApiCollectionsRetrieveRequest {
	r.includeRemoteData = &includeRemoteData
	return r
}
func (r ApiCollectionsRetrieveRequest) RemoteFields(remoteFields string) ApiCollectionsRetrieveRequest {
	r.remoteFields = &remoteFields
	return r
}
func (r ApiCollectionsRetrieveRequest) ShowEnumOrigins(showEnumOrigins string) ApiCollectionsRetrieveRequest {
	r.showEnumOrigins = &showEnumOrigins
	return r
}

func (r ApiCollectionsRetrieveRequest) Execute() (Collection, *_nethttp.Response, error) {
	return r.ApiService.CollectionsRetrieveExecute(r)
}

/*
 * CollectionsRetrieve Method for CollectionsRetrieve
 * Returns a `Collection` object with the given `id`.
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id
 * @return ApiCollectionsRetrieveRequest
 */
func (a *CollectionsApiService) CollectionsRetrieve(ctx _context.Context, id string) ApiCollectionsRetrieveRequest {
	return ApiCollectionsRetrieveRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

/*
 * Execute executes the request
 * @return Collection
 */
func (a *CollectionsApiService) CollectionsRetrieveExecute(r ApiCollectionsRetrieveRequest) (Collection, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Collection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "CollectionsApiService.CollectionsRetrieve")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/collections/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", _neturl.PathEscape(parameterToString(r.id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xAccountToken == nil {
		return localVarReturnValue, nil, reportError("xAccountToken is required and must be specified")
	}

	if r.includeRemoteData != nil {
		localVarQueryParams.Add("include_remote_data", parameterToString(*r.includeRemoteData, ""))
	}
	if r.remoteFields != nil {
		localVarQueryParams.Add("remote_fields", parameterToString(*r.remoteFields, ""))
	}
	if r.showEnumOrigins != nil {
		localVarQueryParams.Add("show_enum_origins", parameterToString(*r.showEnumOrigins, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["X-Account-Token"] = parameterToString(*r.xAccountToken, "")
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["tokenAuth"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
