/*
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_ticketing_client

import (
	"encoding/json"
)

// RemoteField struct for RemoteField
type RemoteField struct {
	Value map[string]interface{} `json:"value,omitempty"`
	RemoteFieldClass NullableString `json:"remote_field_class,omitempty"`
	// raw json response by property name
	ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewRemoteField instantiates a new RemoteField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteField() *RemoteField {
	this := RemoteField{}
	return &this
}

// NewRemoteFieldWithDefaults instantiates a new RemoteField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteFieldWithDefaults() *RemoteField {
	this := RemoteField{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RemoteField) GetValue() map[string]interface{} {
	if o == nil  {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RemoteField) GetValueOk() (*map[string]interface{}, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return &o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *RemoteField) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *RemoteField) SetValue(v map[string]interface{}) {
	o.Value = v
}

// GetRemoteFieldClass returns the RemoteFieldClass field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RemoteField) GetRemoteFieldClass() string {
	if o == nil || o.RemoteFieldClass.Get() == nil {
		var ret string
		return ret
	}
	return *o.RemoteFieldClass.Get()
}

// GetRemoteFieldClassOk returns a tuple with the RemoteFieldClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RemoteField) GetRemoteFieldClassOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RemoteFieldClass.Get(), o.RemoteFieldClass.IsSet()
}

// HasRemoteFieldClass returns a boolean if a field has been set.
func (o *RemoteField) HasRemoteFieldClass() bool {
	if o != nil && o.RemoteFieldClass.IsSet() {
		return true
	}

	return false
}

// SetRemoteFieldClass gets a reference to the given NullableString and assigns it to the RemoteFieldClass field.
func (o *RemoteField) SetRemoteFieldClass(v string) {
	o.RemoteFieldClass.Set(&v)
}
// SetRemoteFieldClassNil sets the value for RemoteFieldClass to be an explicit nil
func (o *RemoteField) SetRemoteFieldClassNil() {
	o.RemoteFieldClass.Set(nil)
}

// UnsetRemoteFieldClass ensures that no value is present for RemoteFieldClass, not even an explicit nil
func (o *RemoteField) UnsetRemoteFieldClass() {
	o.RemoteFieldClass.Unset()
}

func (o RemoteField) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.RemoteFieldClass.IsSet() {
		toSerialize["remote_field_class"] = o.RemoteFieldClass.Get()
	}
	return json.Marshal(toSerialize)
}

func (v *RemoteField) UnmarshalJSON(src []byte) error {
    type RemoteFieldUnmarshalTarget RemoteField

	var intermediateResult RemoteFieldUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = RemoteField(intermediateResult)
	return nil
}
type NullableRemoteField struct {
	value *RemoteField
	isSet bool
}

func (v NullableRemoteField) Get() *RemoteField {
	return v.value
}

func (v *NullableRemoteField) Set(val *RemoteField) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteField) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteField(val *RemoteField) *NullableRemoteField {
	return &NullableRemoteField{value: val, isSet: true}
}

func (v NullableRemoteField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


