/*
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_ticketing_client

import (
    "testing"
)

func TestDeserializeLinkedAccountCondition(t *testing.T) {
    /*
    No test json responses were defined for LinkedAccountCondition
    */
}
