/*
 * Merge Ticketing API
 *
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * API version: 1.0
 * Contact: hello@merge.dev
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package merge_ticketing_client

import (
	"encoding/json"
)

// TicketEndpointRequest struct for TicketEndpointRequest
type TicketEndpointRequest struct {
	Model TicketRequest `json:"model"`
    // raw json response by property name
    ResponseRaw map[string]json.RawMessage `json:"-"`
}

// NewTicketEndpointRequest instantiates a new TicketEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTicketEndpointRequest(model TicketRequest) *TicketEndpointRequest {
	this := TicketEndpointRequest{}
	this.Model = model
	return &this
}

// NewTicketEndpointRequestWithDefaults instantiates a new TicketEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTicketEndpointRequestWithDefaults() *TicketEndpointRequest {
	this := TicketEndpointRequest{}
	return &this
}

// GetModel returns the Model field value
func (o *TicketEndpointRequest) GetModel() TicketRequest {
	if o == nil {
		var ret TicketRequest
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *TicketEndpointRequest) GetModelOk() (*TicketRequest, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *TicketEndpointRequest) SetModel(v TicketRequest) {
	o.Model = v
}

func (o TicketEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["model"] = o.Model
	}
	return json.Marshal(toSerialize)
}

func (v *TicketEndpointRequest) UnmarshalJSON(src []byte) error {
    type TicketEndpointRequestUnmarshalTarget TicketEndpointRequest

	var intermediateResult TicketEndpointRequestUnmarshalTarget
	var err1 = json.Unmarshal(src, &intermediateResult)
    if err1 != nil {
        return err1
    }
    var err2 = json.Unmarshal(src, &intermediateResult.ResponseRaw)
	if err2 != nil {
		return err2
	}

	*v = TicketEndpointRequest(intermediateResult)
	return nil
}
type NullableTicketEndpointRequest struct {
	value *TicketEndpointRequest
	isSet bool
}

func (v NullableTicketEndpointRequest) Get() *TicketEndpointRequest {
	return v.value
}

func (v *NullableTicketEndpointRequest) Set(val *TicketEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTicketEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTicketEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTicketEndpointRequest(val *TicketEndpointRequest) *NullableTicketEndpointRequest {
	return &NullableTicketEndpointRequest{value: val, isSet: true}
}

func (v NullableTicketEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTicketEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	var err1 = json.Unmarshal(src, &v.value)
    if err1 != nil {
        return err1
    }
    return json.Unmarshal(src, &v.value.ResponseRaw)
}


